### ISSUE TITLE
Unit-тестирование

### ISSUE THREAD

**Issue by lenoleuum** [lenoleuum/bmstu-team-dev#10]
Задача:
Необходимо написать unit-тесты к компонентам доступа к данными и бизнес логики серверной части приложения. 

- [x] unit-тесты для компонента доступа к данным;
- [x] unit-тесты для компонента бизнес-логики.

Рекомендуемое название ветки - feature/4. При написании тестов необходимо замокать бд!

Критерий выполнения:
Компоненты серверной части покрыты unit-тестами.

**Comment by Juliasunn** [comment]
Тестировалась только серверная часть приложения, поскольку на стороне клиента происходит только вызов API сервера.
