### ISSUE TITLE
Интеграционное тестирование

### ISSUE THREAD

**Issue by lenoleuum** [lenoleuum/bmstu-team-dev#11]
Задача:
Необходимо написать интеграционные тесты для компонентов доступа к данным и бизнес-логики (протестировать их взаимодействие).
Рекомендуемое название ветки - feature/5.

Критерий выполнения:
Компоненты серверной части покрыты интеграционными тестами.

**Comment by Juliasunn** [comment]
Сделано

**Comment by Juliasunn** [comment]
Тестировалась только серверная часть приложения, поскольку на стороне клиента происходит только вызов API сервера.
