### ISSUE TITLE
Создать страницу авторизации

### ISSUE THREAD

**Issue by ArKarina** [lenoleuum/bmstu-team-dev#16]
Задача:
Необходимо реализовать страницу авторизации приложения в соответствии с макетом Figma #8. Достаточно адаптивной десктопной версии (корректное отображение в диапазоне от 1280 x 768 до 4k). Все повторяющиеся элементы интерфейса нужно вынести в отдельные компоненты (панели, кнопки, поля и формы ввода и т.д).Также необходимо добавить поддержку jwt-авторизации.
Рекомендуемое название ветки - feature/3.1.

- [x] форма ввода логина и пароля
- [x] поддержка jwt-авторизации
- [x] переход на главную страницу приложения

Критерий выполнения:
Работающая и хотя бы отдаленно напоминающая макет страница авторизации.

**Comment by VLittleMonster** [comment]
Done✅
