### ISSUE TITLE
Создать страницу регистрации

### ISSUE THREAD

**Issue by ArKarina** [lenoleuum/bmstu-team-dev#17]
Задача:
Необходимо реализовать страницу регистрации приложения в соответствии с макетом Figma https://github.com/lenoleuum/bmstu-team-dev/issues/8. Достаточно адаптивной десктопной версии (корректное отображение в диапазоне от 1280 x 768 до 4k). Все повторяющиеся элементы интерфейса нужно вынести в отдельные компоненты (панели, кнопки, поля и формы ввода и т.д).
Рекомендуемое название ветки - feature/3.2.

- [x] сверстать страницу регистрации
- [x] форма ввода логина и пароля
- [x] переход на главную страницу

Критерий выполнения:
Работающая и хотя бы отдаленно напоминающая макет страница регистрации.

**Comment by VLittleMonster** [comment]
Done✅
