### ISSUE TITLE
Создать главную страницу приложения

### ISSUE THREAD

**Issue by ArKarina** [lenoleuum/bmstu-team-dev#18]
Задача:
Необходимо реализовать главную страницу приложения в соответствии с макетом Figma https://github.com/lenoleuum/bmstu-team-dev/issues/8. Достаточно адаптивной десктопной версии (корректное отображение в диапазоне от 1280 x 768 до 4k). Все повторяющиеся элементы интерфейса нужно вынести в отдельные компоненты (панели, кнопки, поля и формы ввода и т.д).
Рекомендуемое название ветки - feature/3.3.

- [x] список типов
- [x] список персонажей 
- [x] тест на личность
- [x] профиль пользователя

Критерий выполнения:
Работающая и хотя бы отдаленно напоминающая макет главная страница.

**Comment by VLittleMonster** [comment]
Done✅
