### ISSUE TITLE
Создание компонента API

### ISSUE THREAD

**Issue by lenoleuum** [lenoleuum/bmstu-team-dev#23]
Задача:
Необходимо реализовать компонент API серверной части приложения.
Рекомендуемое название ветки - feature/2.3

Необходимо реализовать:

- [x] модели: AuthenticateRequest - запрос на авторизацию, AuthenticateResponse - отправляет в ответ в случае успешной авторизации;
- [x] контроллеры, которые обслуживают endpoints, описанные в [swagger](https://app.swaggerhub.com/apis/lenoleuum/MBTI/2.0).

**Comment by Artvin2001** [comment]
Готово

**Comment by lenoleuum** [comment]
done
