### ISSUE TITLE
Подготовка макета клиентской части

### ISSUE THREAD

**Issue by lenoleuum** [lenoleuum/bmstu-team-dev#8]
Задача:
Необходимо составить макет страниц клиентской части приложения в Figma в соответствии с пользовательскими сценариями из [тз](https://github.com/lenoleuum/bmstu-team-dev/wiki/ТЗ). Также необходимо настроить навигацию между экранами (prototype).
В комментарии рекомендуется прикрепить ссылку на макет.

Критерий выполнения:
Макет в Figma, который можно будет потыкать в режиме просмотра.

**Comment by ArKarina** [comment]
https://www.figma.com/file/DGEgnA22vOR1XgkMBU9P7b/mbtiworld?node-id=0-1&t=cKvDWnWRHj4zjvbr-0
