### ISSUE TITLE
Разработка frontend части приложения

### ISSUE THREAD

**Issue by lenoleuum** [lenoleuum/bmstu-team-dev#9]
Задача:
Необходимо реализовать клиентскую часть приложения в соответствии с макетом Figma #8. Достаточно адаптивной десктопной версии (корректное отображение в диапазоне от 1280 x 768 до 4k). Все повторяющиеся элементы интерфейса нужно вынести в отдельные компоненты (панели, кнопки, поля и формы ввода и т.д).Также необходимо добавить поддержку jwt-авторизации. 
Рекомендуемое название ветки - feature/3.

Критерий выполнения:
Работающая и хотя бы отдаленно напоминающая макет клиентская часть приложения.

**Comment by lenoleuum** [comment]
@ArKarina опиши подробнее git flow для фронта, пожалуйста.

**Comment by ArKarina** [comment]
Ветка feature/3 является основной. Вся разработка проводится в в дочерних ветках 3.1, 3.2, 3.3, ... Затем все эти ветки вливаются в основную feature/3.

**Comment by ArKarina** [comment]
done
